// let a=2

// error handling
try {
    console.log(a);
} catch (error) {
    console.log("somthing went wrong: "+error)
}


